### PR TITLE
#161966998 Upgrade Django app from Django 1.10 to Django 2.1

### PR DESCRIPTION
**Pull request by GransonO**
#### What does this PR do?
- Updates the django packages to the most recent 

#### Description of Task to be completed?
- Update the django package to the most recent versions
- Edit some of the code base to fit the new packages standards

#### How should this be manually tested?
```
1. Git clone the repo using this command:
   `https://github.com/andela/ah-jumanji.git`

2. Install all packages from requirements.txt
  `pip install -r requirements.txt`

3. Create migrations and migrate 
   `python manage.py makemigrations` && `python manage.py migrate`

4. Run the application
  `python manage.py runserver`

5. Access the page through: 
   `http://127.0.0.1:8000`
```
#### Any background context you want to provide?
- Using the most recent packages for development purposes is best practice as it gives one the advantage of using improved resources with regards to security and other core functionalities 

#### What are the relevant pivotal tracker stories?
[#161966998](https://www.pivotaltracker.com/n/projects/2225604)

#### Screenshots (if appropriate)
screenshot 2018-11-29 at 13 10 40

### CODE REVIEW

**Review by mashafrancis — APPROVED** [review]
Awesome work. Looks good to be used.

**Review by ghost — APPROVED** [review]
LGTM.
Except, and this is just semantics, you could improve on readability of the code by adding a space btn `... admin.site.urls` and `name=admin` on `line 20` of `authors/urls.py`.

**Review by fabzer0 — APPROVED** [review]

**Comment by ghost** [comment]
@GransonO , there's a template we developed for Pull Requests. It includes a checklist at the bottom, which you're supposed to include in the PR. Check it out here: https://github.com/andela/ah-jumanji/blob/dba2e3c3dacbbdf0adcd82bb8b7fc9200a29071c/.github/jumanji_pull_request_template.md

**Review by EmmanuelBeja — APPROVED** [review]
works great

**Comment by GransonO** [comment]
> https://github.com/andela/ah-jumanji/blob/dba2e3c3dacbbdf0adcd82bb8b7fc9200a29071c/.github/jumanji_pull_request_template.md

`Well observed. Thank you for the heads up.`

**Pull request merged**
