### PR TITLE
#161967013 Add Functionality for Creating and Editing User Profiles

### PR DESCRIPTION
**Pull request by ghost**
#### What does this PR do?
This PR is a build out of the `profiles` app, which allows users to create and edit a `Profile`.
#### Description of Task to be completed?
With this PR:
- a profile is auto-generated for a user on sign-up
- a logged in user can update the individual elements on their profile
#### How should this be manually tested?
It can be tested on `Postman` as below:
1. Run the following commands in `Terminal`
```
git clone git@github.com:andela/ah-jumanji.git
git checkout ft-user-profiles-161967013
virtualenv venv && source venv/bin/activate
pip install -r requirements.txt
echo "DATABASE_URL=postgres://{postgres-db-username}:{postgres-db-password}@localhost/ah_jumanji" > .env
python manage.py makemigrations && python manage.py migrate
python manage.py makemigrations profiles && python manage.py migrate profiles
python manage.py runserver
```
2. Send a `POST {your-server-root}:8000/api/users/register` request with a payload similar to:
```
{"user": {
   "username": "cmithamo",
   "email": "cmithamo@mymail.com",
   "password": "strong-password"
   }
}
```
to register a `User` and generate an auth token
3. With the auth token generated, send a `GET {your-server-root}:8000/api/users/profiles/`  request to view the auto-generated profile for the user just now created.
4. To update the profile, send a `PUT {your-server-root}:8000/api/users/profiles/` request with the same auth token, and a payload similar to
```
{
    "profile": {
        "user": 4,
        "first_name": "Cee",
        "last_name": "Mithamo",
        "bio": "What's in a bio, really?",
        "profile_photo": "",
        "country": "KEN",
        "phone_number": "700123456",
        "twitter_handle": "@cmithamo",
        "website": ""
    }
}
```
5. Run the `tests` using `pytest` with the command `pytest` or `pytest -v` for verbose output.

#### What are the relevant pivotal tracker stories?
[#161967013](https://www.pivotaltracker.com/story/show/161967013)
#### Screenshots (if appropriate)
`1. Register a User - POST {your-server-root}:8000/api/users/register`
image

`2. View auto-generated profile - GET {your-server-root}:8000/api/users/profiles/`
image

`3. Update Profile - PUT {your-server-root}:8000/api/users/profiles/`
image

`4. View profile after updating - GET {your-server-root}:8000/api/users/profiles/`
image

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Review by GransonO — COMMENTED** [review]
The work looks good enough. Some `hound issues to look into`. Since its a work in progress PR, respond on the `expected completion time`.

**Review by mashafrancis — COMMENTED** [review]
Awesome work. I have tested the functionality and it works as expected.

**Review by mashafrancis — APPROVED** [review]

**Review by GransonO — APPROVED** [review]
All looks good. Need to be merged to complete mine cc @mirr254

**Review by gitau-kinuthia — COMMENTED** [review]
The functionality looks good, however, the `update_profile` method in the profile model seems hanging with a docstring only and no accompanying logic.check on this or remove it all the same

**Review by EmmanuelBeja — APPROVED** [review]

**Pull request merged**
