### PR TITLE
#161967005 Link coveralls to project repo on github

### PR DESCRIPTION
**Pull request by fabzer0**
#### What does this PR do?
   - This PR links this repo to coveralls to show test coverage.

#### Any background context you want to provide?
   - The markdown generated by coveralls is put in a readme file.
   - By doing so, the coverage badge can now be displayed in the repo. 

#### What are the relevant pivotal tracker stories?
   [#161967005](https://www.pivotaltracker.com/story/show/161967005)

#### Screenshots
screenshot 2018-11-27 at 12 09 37

### CODE REVIEW

**Comment by mashafrancis** [comment]
Great work. Maybe a suggestion, to add a screenshot of the task finished.

**Comment by fabzer0** [comment]
On it.

**Comment by ghost** [comment]
This looks OK, except, in the `README` the `Coveralls` badge points a to a non-existent branch ...
image

**Comment by fabzer0** [comment]
True. Let me rectify that

**Comment by fabzer0** [comment]
@dmithamo1. Is it okay to link the develop branch instead of linking the mini-branch on coveralls README.md markdown?

**Comment by GransonO** [comment]
> @dmithamo1. Is it okay to link the develop branch instead of linking the mini-branch on coveralls README.md markdown?

Yes, that should do. Since all tests and coverage for the whole project will be reported from that branch

**Comment by gwako94** [comment]
> @dmithamo1. Is it okay to link the develop branch instead of linking the mini-branch on coveralls README.md markdown?

> @fabischolasi  Yes you should reference the develop branch in you coverall badge.

**Comment by ghost** [comment]
> > @dmithamo1. Is it okay to link the develop branch instead of linking the mini-branch on coveralls README.md markdown?
> 
> Yes, that should do. Since all tests and coverage for the whole project will be reported in that branch

Yea, I think so too. link to `develop`

**Comment by fabzer0** [comment]
Great.

**Review by mashafrancis — COMMENTED** [review]
The PR looks good to me now with the changes.

**Comment by EmmanuelBeja** [comment]
looks good. nice job.

**Review by EmmanuelBeja — APPROVED** [review]

**Review by gwako94 — APPROVED** [review]
Looks good to merge.

**Review by ghost — APPROVED** [review]

**Pull request merged**
