### PR TITLE
#161966997 Research and choose css framework for creating mock ups(plus create mockup)

### PR DESCRIPTION
**Pull request by EmmanuelBeja**
#### What does this PR do?
Research and choose CSS framework for creating mockups(plus create mockup)
```
Findings:
SEMANTIC UI.
Modern front-end development framework, powered by LESS and jQuery. It has a sleek, subtle, and flat design look that provides a lightweight user experience
Advantages:
- Semantic solutions: Offers Semantic class names making it easy to learn.
- Reduced load time. Lets user load components of choice reducing load time in comparison to other CSS frameworks.
Disadvantages:
- Executing custom workaround can be challenging since it uses javascript customisation.
- The package's files are large(larger than bootstrap).

Bootstrap.
HTML, CSS, Js based framework originally created by a developer and designer at Twitter.
Advantages:
- Responsive. Styling adapts perfectly with almost all devices screens.
- Consistency. Works well with all browsers.
- Quick development and efficient. Easy to learn and customise. Each component is also configured to ensure good performance.
Disadvantages:
- Package's Size of files too large.
- Could lead to messy work due to dependency on CSS classes.

Materialize.
Materialize is a CSS framework based on Google's Material Design
Advantages:
- Speeds up development. It offers default stylings.
- UX-focused(specifically for mobile web applications). Has components that provide more feedback to users.
- Easy to use. Has detailed documentation and code examples.
- Light file size.
Disadvantages:
- Little support for materialize.
- Opinionated making it harder to customise.
- Poor GRID system

 Note:
Semantic classes - Semantic Class names explain why the class is used and what it is. They don't explain it's behaviour.
```
#### References:
- [Link A](https://www.payoda.com/blog/is-materialize-better-than-bootstrap-or-semantic-ui/)
- [Link B](https://stackshare.io/stackups/bootstrap-vs-materialize-vs-semantic-ui)

Based on finding above we decided to go with bootstrap

#### Description of Task to be completed?
Research and Choose one CSS framework that you will consistently use for the entirety of the project. This will be used to construct dumb Mockups for demonstration of Backend functionality & eventually in implementing the Frontend.
##### How should this be manually tested?
```
clone project https://github.com/andela/ah-jumanji.git
git clone https://github.com/andela/ah-jumanji.git
cd ah-jumanji
git checkout ch-choose-css-framework-and-create-mockup-161966997
open html pages on a browser

Sitemap
- index.html
- signup.html
- verified.html
- login.html
- forgotpassword.html
- home.html
- createarticle.html
- article.html
- editarticle.html
- userprofile.html
- profile.html
- editprofile.html
```
#### What are the relevant pivotal tracker stories?
[#161966997](https://www.pivotaltracker.com/story/show/161966997)
#### Screenshots (if appropriate)
- index.html
screen shot 2018-12-12 at 18 04 26

- login.html
screen shot 2018-12-12 at 18 05 59

- signup.html
screen shot 2018-12-12 at 18 07 28

- verified.html
screen shot 2018-12-12 at 18 10 40

- forgotpassword.html
screen shot 2018-12-12 at 18 11 47

- home.html
screen shot 2018-12-13 at 12 51 35

- createarticle.html
screen shot 2018-12-13 at 12 55 13

- article.html
screen shot 2018-12-13 at 12 56 45
screen shot 2018-12-13 at 12 57 24

- editarticle.html
screen shot 2018-12-13 at 12 59 58

- userprofile.html
screen shot 2018-12-13 at 13 00 44

- profile.html
screen shot 2018-12-13 at 12 58 11

- editprofile.html
screen shot 2018-12-13 at 12 59 05

#### Checklist:
- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My PR has one commit.

### CODE REVIEW

**Comment by GransonO** [comment]
It would have been great if you could add the live link(your-repo.github.io) to the repo so we could load it to our browsers.(Needs admin access)

**Comment by ghost** [comment]
This is great

**Comment by EmmanuelBeja** [comment]
noted @GransonO. Find it [here](https://emmanuelbeja.github.io/ah-jumaji-ui/home.html)

**Comment by fabischolasi** [comment]
Why did you remove me as a reviewer

**Comment by EmmanuelBeja** [comment]
you are slow to respond @fabischolasi

**Comment by fabischolasi** [comment]
It is still early in the day

**Comment by ghost** [comment]
@EmmanuelBeja , I just noticed that clicking the `logout` btn redirects to `logout.html`, which `github.io` reports as a `404`. Error?

**Comment by EmmanuelBeja** [comment]
Nice observation @dmithamo1 . Am fixing it.

**Comment by fabzer0** [comment]
The mockup looks great

**Comment by EmmanuelBeja** [comment]
Sorted out the issue @dmithamo1

**Pull request merged**
