### PR TITLE
#161967007 Add Swagger API documentation

### PR DESCRIPTION
**Pull request by mashafrancis**
#### What does this PR do?
This PR adds swagger documentation for the app endpoints
#### Description of Task to be completed?
- install Django rest swagger module
- configure Django settings and URLs for swagger documentation
- refactor API resources for generics
#### How should this be manually tested?
On the terminal, run the following commands:
```
$ git clone https://github.com/andela/ah-jumanji.git
$ cd ah-jumanji
$ python3 -m venv venv
$ source venv/bin/activate
$ git checkout ft-document-swagger-api-161967007
(venv) $ pip install -r requirements.txt
(venv) $ touch .env
(venv) $ echo "DATABASE_URL=postgres://username:password@localhost/db_name" >> .env
(venv) $ echo "DEBUG=on" >> .env
(venv) $ python manage.py migrate
(venv) $ python manage.py runserver
```
On your browser, navigate to:
```
{your-server-root}:8000
```
#### Any background context you want to provide?
- Django Rest Swagger documentation [here](https://django-rest-swagger.readthedocs.io/en/latest/)
#### What are the relevant pivotal tracker stories?
[#161967007](https://www.pivotaltracker.com/story/show/161967007)
#### Screenshots (if appropriate)

1. Swagger UI before authentication
screenshot 2018-12-11 at 23 47 04

2. Swagger UI authenticating
screenshot 2018-12-11 at 23 47 58

3. Swagger UI logged in user
screenshot 2018-12-11 at 23 48 35

#### Checklist:
- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This is neat. Do we have the docs hosted anywhere, like on `Heroku`?

**Comment by mashafrancis** [comment]
@dmithamo1 Thanks. I am expecting when @GransonO's work will be merged, the swagger documentation will be loaded there as well by default. We have already worked on it together and I'm confident it will work as expected once he completes his part.

**Review by GransonO — APPROVED** [review]
Pretty neat work. I hope during the merge there won't be too much to change due to the `view - generics class` difference.

**Review by gwako94 — APPROVED** [review]
Looking good to merge

**Review by gitau-kinuthia — APPROVED** [review]
The swagger documentation is working great for all endpoints. It looks good to me

**Review by fabzer0 — APPROVED** [review]

**Review by mirr254 — COMMENTED** [review]
LGTM

**Pull request merged**
