### PR TITLE
#161967002 Integrate Travis CI and add README badge

### PR DESCRIPTION
**Pull request by ghost**
#### What does this PR do?
This `PR` adds a Travis CI badge on the project's `README`.
#### Description of Task to be completed?
Integrating `Travis CI` automates the build process. That is, whenever new functionality is added, tests are auto-run, to see whether how it impacts on the rest of the project.
#### How should this be manually tested?
```
This will be testable when functionality starts being implemented.
```
#### What are the relevant pivotal tracker stories?
[#161967002](https://www.pivotaltracker.com/story/show/161967002)
#### Screenshots (if appropriate)
image

#### Checklist:
- [x] At least 2 people have reviewed my PR
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Review by gwako94 — APPROVED** [review]
Yes this can be merged.

**Review by EmmanuelBeja — COMMENTED** [review]
Looks good. Good work

**Review by fabzer0 — APPROVED** [review]

**Review by EmmanuelBeja — APPROVED** [review]

**Review by GransonO — APPROVED** [review]
LGTM

**Comment by kipropbrian** [comment]
A different issue but the checklist is not formatted correctly, you need to create a PR to fix that. The checklist should be a clickable checkbox.

**Comment by ghost** [comment]
> A different issue but the checklist is not formatted correctly, you need to create a PR to fix that. The checklist should be a clickable checkbox.

GitHub says that placing an `x` within the square brackets is how to mark an item on the checklist as done. This is what you meant, right?

**Pull request merged**
