### PR TITLE
#161967010 Verify User Registration through Email

### PR DESCRIPTION
**Pull request by fabzer0**
#### What does this PR do?
 - This PR verifies a new user during registration.

#### Description of Task to be completed?
 - When a new user signs up, they get an email together with a link to a page that will verify them.
 - On clicking, if the link is valid, verification will be successful. The reverse is also True.

#### How should this be manually tested?

1. `git clone` this repo to your local machine.
2. install virtual environment and activate it inside the directory created.
3. run `pip install -r requirements.txt`
4. include the following in the .env file:
```       
DATABASE_URL="postgres://<username>:<password>@localhost/<dbname>"
export PROTOCOL="http://"
export EMAIL_HOST_USER="<jumanjidevs32@gmail.com>"
export EMAIL_HOST_PASSWORD="<jumanji@32>"
DEBUG=True
```
5. run `python manage.py makemigrations && python manage.py migrate`.
6. run `python manage.py runserver` and navigate to the link below.
7. By using [postman](https://www.getpostman.com/apps), input the following URL:
`http://localhost:8000/api/users/register`
9. Input user data that is the username, email and password wrapped in another 
    dictionary with user.
10. Click send and an email will be sent. Click on the link and you will be navigated 
    to the page where your activation will occur. If activation is successful, the message,
   Activation is successful will be returned else, Activation link is invalid.

#### What are the relevant pivotal tracker stories?
[#161967010](https://www.pivotaltracker.com/n/projects/2225604)

#### Screenshots (if appropriate)
screenshot 2018-12-06 at 14 03 15
----------------------------------------------***---------------------------------------------------
screenshot 2018-12-06 at 14 05 34

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Comment by mashafrancis** [comment]
Nice work. A few missing instructions on the readme, to checkout to your branch, database configuration and the environment variables need to be added as well.
Then also add some docstrings to the methods you have created in the code and tests written.

**Review by ghost — COMMENTED** [review]
This introduces changes that require re-writing of most of the other PR's. I would recommend that it be merged last.

**Comment by gwako94** [comment]
Kindly check on the tests

**Review by gitau-kinuthia — COMMENTED** [review]
The feature works just fine, however on the checks and make sure they are passing. Also, the registration email sent, it should become invalid after it's used as it should not be able to activate an already active user.

**Review by ghost — APPROVED** [review]
Tested this. Works great!

**Review by mashafrancis — APPROVED** [review]
Awesome work.

**Review by EmmanuelBeja — APPROVED** [review]

**Pull request merged**
