### PR TITLE
#161967002 Setup Travis CI

### PR DESCRIPTION
**Pull request by ghost**
#### What does this PR do?
   - This PR integrates `Travis CI` as a continuous integration tool to report build status with each push.

#### Any background context you want to provide?
   - Travis CI reports an error when `Python 3.7` is added as a supported Python version. `Python 3.7` is therefore not currently supported for this project.
   - No functionality/tests have been written yet, hence [travisci/ah-jumanji](https://travis-ci.org/andela/ah-jumanji) currently reports that the build `errored`. Also, the badge reports that build is `unknown` because of this.

#### What are the relevant pivotal tracker stories?
   [#161967002](https://www.pivotaltracker.com/story/show/161967002)

#### Screenshots
`1. Project on Travis CI`
image

`2. README`
image

### CODE REVIEW

**Comment by GransonO** [comment]
Just a point to note, did you add all members to the Travis mailbox so as to receive notice on build failure or success?

**Comment by ghost** [comment]
> Just a point to note, did you add all members to the Travis mailbox so as to receive notice on build failure or success?

I did not. Let me look into that

**Comment by GransonO** [comment]
> > Just a point to note, did you add all members to the Travis mailbox so as to receive notice on build failure or success?
> 
> I did not. Let me look into that

Alternatively, I think integrating Travis to the `slack channel` will be better, so we can all get the notification from one place. 

The urls to add to the the .yml file are:
` notifications:
    slack: andela:RCO3odsl7AvykS4GYVFIsa1E`

**Comment by gitau-kinuthia** [comment]
This is great. However, change the test runner to pytest. This is more versatile and will allow us to run and report coverage on our tests more easily.

**Comment by ghost** [comment]
> This is great. However, change the test runner to pytest. This is more versatile and will allow us to run and report coverage on our tests more easily.

Got it. Refactoring to `pytest` as the test runner of choice.

**Review by EmmanuelBeja — COMMENTED** [review]
Just asking. Why is the badge saying build unknown?

**Comment by dmithamo1** [comment]
> > This is great. However, change the test runner to pytest. This is more versatile and will allow us to run and report coverage on our tests more easily.
> 
> Got it. Refactoring to `pytest` as the test runner of choice.

**Comment by ghost** [comment]
@EmmanuelBeja ,
There are no tests to run yet.

**Comment by ghost** [comment]
> > > Just a point to note, did you add all members to the Travis mailbox so as to receive notice on build failure or success?
> > 
> > 
> > I did not. Let me look into that
> 
> Alternatively, I think integrating Travis to the `slack channel` will be better, so we can all get the notification from one place.
> 
> The urls to add to the the .yml file are:
> ` notifications: slack: andela:RCO3odsl7AvykS4GYVFIsa1E`

Neat. Working on this

**Review by mashafrancis — APPROVED** [review]
Awesome. I feel its good to me. It's better at least we also get build notifications on Slack. Nice job.

**Comment by fabischolasi** [comment]
Great work. But an add on here. Installing dependencies via pip can make up a large portion of build duration. Caching the pip between builds drastically reduces the time a build takes to run.

**Review by fabzer0 — COMMENTED** [review]
Great work. But an add on here. Installing dependencies via pip can make up a large portion of build duration. Caching the pip between builds drastically reduces the time a build takes to run.

**Comment by gwako94** [comment]
The set up looks good for now but keep an open mind because as the project grows a lot will change on the travis configuration.

**Review by fabzer0 — APPROVED** [review]

**Review by EmmanuelBeja — APPROVED** [review]

**Pull request merged**
