### PR TITLE
#161967002 Setup Travis CI

### PR DESCRIPTION
**Pull request by ghost**
#### What does this PR do?
This `PR` adds a Travis CI badge on the project's `README`.
#### Description of Task to be completed?
Integrating `Travis CI` automates the build process. That is, whenever new functionality is added, tests are auto-run, to see whether how it impacts on the rest of the project.
#### How should this be manually tested?
```
This will be testable when functionality starts being implemented.
```
#### What are the relevant pivotal tracker stories?
[#161967002](https://www.pivotaltracker.com/story/show/161967002)
#### Checklist:
- [ - ] My code follows the style guidelines of this project
- [  ] At least 2 people have reviewed my PR
- [ - ] I have commented my code, particularly in hard-to-understand areas
- [ - ] I have made corresponding changes to the documentation
- [ - ] My changes generate no new warnings
- [ - ] I have added tests that prove my fix is effective or that my feature works
- [ - ] New and existing unit tests pass locally with my changes
- [ - ] My PR has one commit.

### CODE REVIEW

**Review by EmmanuelBeja — COMMENTED** [review]
Has merge conflicts. Kindly check on that.

**Review by mashafrancis — CHANGES_REQUESTED** [review]
Kindly check on the merge conflicts and it'll be good.

**Review by GransonO — CHANGES_REQUESTED** [review]
There are some merge issues that need looking into.

**Review by gwako94 — CHANGES_REQUESTED** [review]
Fix merge conflict, Use Git rebase.

**Comment by ghost** [comment]
Duly noted @EmmanuelBeja , @mashafrancis , @gwako94 , @GransonO .
Working on that.

**Pull request closed without merging**
