### PR TITLE
#161966961 Setup Hound CI 

### PR DESCRIPTION
**Pull request by ghost**
#### What does this PR do?
This PR integrates the `Hound CI` code style checker.
#### Description of Task to be completed?
With this in place, when a PR is raised, code is automatically checked for style consistencies. The style checker (`Hound CI`) adds comments where there are style inconsistencies.
#### How should this be manually tested?
```
To test this, commit code that includes style inconsistencies.
Hound CI will only add comments if there are style inconsistencies.

This will take effect when PR's are raised, going forward.
```
#### What are the relevant pivotal tracker stories?
[#161966961](https://www.pivotaltracker.com/story/show/161966961)
#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Review by gwako94 — APPROVED** [review]
Hound integration OK.

**Review by mashafrancis — APPROVED** [review]
Nice. Looks OK to me.

**Review by EmmanuelBeja — APPROVED** [review]
I see flake8 enabled and It works fine.   nice work

**Comment by fabzer0** [comment]
Is there the need of `questions`, `Any background context you want to provide?` and `screenshots`  to be present if they are not provided in the PR body?

**Comment by GransonO** [comment]
This may be hard to fully confirm if it is working as expected since we still have no PR raised for the hound to woof! However great work breakdown and explanation on the PR. 
**_`LGTM`_**

**Pull request merged**
